name: Forex Signal Bot
on:
  schedule:
    - cron: '*/5 * * * *' # هر ۵ دقیقه یک‌بار اجرا می‌شود
  workflow_dispatch: # امکان اجرای دستی (گزارش لحظه‌ای)

permissions:
  contents: write # اجازه ذخیره دیتابیس در گیت‌هاب

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Copy Code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Libraries
        run: pip install pyTelegramBotAPI requests pandas

      - name: Run Bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          CTRADER_ACCESS_TOKEN: ${{ secrets.CTRADER_ACCESS_TOKEN }}
          CTRADER_CLIENT_ID: ${{ secrets.CTRADER_CLIENT_ID }}
          CTRADER_CLIENT_SECRET: ${{ secrets.CTRADER_CLIENT_SECRET }}
          CTRADER_ACCOUNT_ID: ${{ secrets.CTRADER_ACCOUNT_ID }}
        run: python main.py

      - name: Save Database Changes
        run: |
          git config --local user.email "bot@github.com"
          git config --local user.name "Journal Bot"
          git add journal.json
          git commit -m "Update trade journal" || exit 0
          git push
